baseURL = "https://hicke.se/"
title = "hicke.se"
theme = "PaperMod"
enableRobotsTXT = true

[[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 10
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowShareButtons = false
  ShowRssButtonInSectionTermList = true
  ShowToc = false
  comments = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
